[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[context.deploy-preview.environment]
  API_URL = "https://api.dev.example.com"
  DATABASE_URL = "postgres://postgres:postgres@postgres:5432/postgres"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
